version: '3'
services:
  web:
    container_name: httpd
    ports:
      - "8080:80"
    networks:
      - net-test
    image: httpd
  web2:
    container_name: httpd2
    ports:
      - "8081:80"
    networks:
      - net-test
    image: httpd
networks:
  net-test: